In [1]:
import numpy as np

**建立数组ndarray**

In [2]:
a1=np.array([1,2,3,4,5,6])#参数为列表
print(a1)

[1 2 3 4 5 6]


In [3]:
type(a1)

numpy.ndarray

In [4]:
a2=np.array((1,2,3,4,5,6))#参数为元组
print(a2)

[1 2 3 4 5 6]


In [5]:
type(a2)

numpy.ndarray

In [6]:
b1=np.array([[100,98,99],[88,78,95]])#二维数组
print(b1)

[[100  98  99]
 [ 88  78  95]]


In [7]:
dem=np.array([(0,0,0),(1,1,1),(2,2,2)])#三维数组
print(dem)

[[0 0 0]
 [1 1 1]
 [2 2 2]]


In [9]:
c1=np.array([[[11,11,11],[12,12,12]],[[21,21,21],[22,22,22]]])#三维数组
print(c1)

[[[11 11 11]
  [12 12 12]]

 [[21 21 21]
  [22 22 22]]]
